//
//  UIColor+Additions.swift
//
//  Generated by Zeplin on 9/21/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {

	@nonobjc class var rewardGreen: UIColor {
		return UIColor(red: 189.0 / 255.0, green: 231.0 / 255.0, blue: 213.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var rewardPurple: UIColor {
		return UIColor(red: 189.0 / 255.0, green: 192.0 / 255.0, blue: 231.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var rewardBlue: UIColor {
		return UIColor(red: 189.0 / 255.0, green: 212.0 / 255.0, blue: 231.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var rewardIce: UIColor {
		return UIColor(red: 189.0 / 255.0, green: 225.0 / 255.0, blue: 231.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var rewardPink: UIColor {
		return UIColor(red: 231.0 / 255.0, green: 189.0 / 255.0, blue: 221.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var rewardRed: UIColor {
		return UIColor(red: 231.0 / 255.0, green: 189.0 / 255.0, blue: 189.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var rewardBrown: UIColor {
		return UIColor(red: 231.0 / 255.0, green: 213.0 / 255.0, blue: 189.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var rewardBlueBorder: UIColor {
		return UIColor(red: 74.0 / 255.0, green: 144.0 / 255.0, blue: 226.0 / 255.0, alpha: 0.3)
	}

	@nonobjc class var rewardIceBorder: UIColor {
		return UIColor(red: 74.0 / 255.0, green: 198.0 / 255.0, blue: 226.0 / 255.0, alpha: 0.3)
	}

	@nonobjc class var rewardGreenBorder: UIColor {
		return UIColor(red: 74.0 / 255.0, green: 226.0 / 255.0, blue: 171.0 / 255.0, alpha: 0.3)
	}

	@nonobjc class var rewardPurpleBorder: UIColor {
		return UIColor(red: 144.0 / 255.0, green: 146.0 / 255.0, blue: 183.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var rewardPinkBorder: UIColor {
		return UIColor(red: 214.0 / 255.0, green: 163.0 / 255.0, blue: 202.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var rewardRedBorder: UIColor {
		return UIColor(red: 232.0 / 255.0, green: 152.0 / 255.0, blue: 152.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var rewardBrownBorder: UIColor {
		return UIColor(red: 235.0 / 255.0, green: 198.0 / 255.0, blue: 148.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var rewardOliveGreen: UIColor {
		return UIColor(red: 231.0 / 255.0, green: 231.0 / 255.0, blue: 189.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var rewardOliveGreenBorder: UIColor {
		return UIColor(red: 194.0 / 255.0, green: 194.0 / 255.0, blue: 89.0 / 255.0, alpha: 1.0)
	}
}
